### ISSUE TITLE
Mapping parks in OpenStreetMap with MappingDC

### ISSUE THREAD

**Issue by geobrando** [OpenGlobe/myamerica-devsummit#14]
The Spring mapathon promoted by the US Chapter of the OpenStreetMap Foudation has the theme of "The Great Outdoors" and coincides with the summit. 

On the first day of the summit, meet up with MappingDC (the local OSM group) and learn about how parks and trails are modeled in OSM, and then let's head outside to the many parks within walking distance of the venue and make sure that they're thoroughly mapped.

The agenda will be posted [here](http://www.meetup.com/MappingDC/events/221396891/)

**Comment by openbrian** [comment]
Please label as "Proposed Session".  @geobrando

**Comment by jimmyrocks** [comment]
The NPMap Team will be releasing a public facing version of its "Places" system for the myAmerica Dev Summit. NPMap team member Jim McAndrew will provide a short presentation about how the public can contribute geospatial data to the National Park Service. He will explain how these contributions will be used within the National Park Service and how we propose to push these contributions into OpenStreetMap.

Jim will be running a local US Chapter OpenStreetMap Mapping party in Colorado. He will be teleconferencing into the DC event to give his presentation and to help map contributors to get started. He will need a few volunteers in DC to help users with questions about the iD editor.

**Comment by geobrando** [comment]
@OpenGlobe.. Gentle reminder that this session will not render on the website without being tagged as "Proposed Session".  Unless I'm missing something, only specific users able to assign tags. Thanks.
